# Use root/example as user/password credentials
version: '3.1'

services:

  redis:
    image: redis:latest
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_PASSWORD: '123456'
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/redis/data

volumes:
  redisdata: